### ISSUE TITLE
Strings "every 1 day" doesn't make sense

### ISSUE THREAD

**Issue by davidvavra** [maltaisn/recurpickerlib#10]
I uploaded strings to GL and started translating. I found that there are many string where quantity "one" doesn't make sense with the number. "Every 1 day" can simply be "Every day". "Every 1 month", "Repeats every 1 year" etc. is the same. Numbers should be removed from these strings.

**Comment by maltaisn** [comment]
You're right that doesn't make sense, I'll change that as soon as I can.

**Comment by maltaisn** [comment]
Fixed it in v1.4.3. I also made the default presets strings rely on the recurrence formatter instead of hard-coding them in strings.xml, so that removed 4 additional strings. And I removed the "Repeats" at the start of the recurrence text because it prevents customization.

**Comment by davidvavra** [comment]
There are still problems in strings.xml - see strings like `rp_frequency_week`. It contains strange values like `<item quantity="one">Every %dweek</item>`. It looks like it should be the same as `rp_format_*`, so all `rp_frequency_*` should be removed?

**Comment by maltaisn** [comment]
No they are used for the frequency input labels. The string is split over `%d` to find what text goes before the input (Every) and what goes after (day). If user enters 1 it should still be splitted. The string is never actually formatted.

**Comment by davidvavra** [comment]
I don't understand, why can't you reuse `rp_format_*` strings for frequency input labels? Plus is inconsistent, `rp_frequency_day` has `<item quantity="one">Every %d day</item>` and `rp_frequency_week` has `<item quantity="one">Every %dweek</item>` (space is missing)

**Comment by maltaisn** [comment]
I can't reuse them because the `one` variant doesn't have the `%d` part needed to split the prefix from the suffix. Look at [this line](https://github.com/maltaisn/recurpickerlib/blob/master/recurpicker/src/main/java/com/maltaisn/recurpicker/RecurrencePickerView.java#L495) you'll understand. The missing space is a typo but it doesn't change anything since split parts are trimmed. I'll fix it but won't make a new release for that.

The goal of the `rp_frequency_*` strings was to avoid having suffix and prefix strings that were inconvenient for translation.

**Comment by davidvavra** [comment]
OK, I understand why you need it. You could reuse translations for quantities >1 and make a special case for quantity one. Imho it would be enough to split string "every day" according to last space character. But I'm not sure if it's true for all languages, to be sure you could add strings like <string>Every|day</string> and explain what the | means in a comment. This will save 8 strings and be more clear to translators.

**Comment by maltaisn** [comment]
It would be a good solution, although that's putting UI logic in the strings as you said earlier. 

I'll change it but won't release immediately, 2 releases in 2 days is enough for now.

**Comment by davidvavra** [comment]
Well saving 8 strings is imho worth it. 

I would argue for another release today. If it's not released, my translators will translate a different format and then we would have to manually change it to all languages when doing a PR. Releasing often doesn't bother people who are using the library. Maybe it's a long process for you?

**Comment by maltaisn** [comment]
No I just thought it would be annoying for people using the library. If you prefer I release immediately I will.

**Comment by davidvavra** [comment]
People don't get any notifications about a new release, unless they specifically subscribe on BinTray. They know about it only when they are viewing build.gradle file and Android Studio shows a warning that there is more recent version available.

**Comment by davidvavra** [comment]
Any news about the release? It's time sensitive, because the translators are already translating the wrong version and are confused.

**Comment by maltaisn** [comment]
I can't do it now, it'll take a few hours.

**Comment by maltaisn** [comment]
Removed the 4 strings in v1.4.4. The strings are split over a `|` character for the frequency input and the character is simply removed elsewhere.

**Comment by davidvavra** [comment]
Thanks a lot, it's uploaded to GL and looks fine.

PS: Next time it would be more efficient to commit code to a separate branch and agree first on the format before doing a bunch of releases.
