### ISSUE TITLE
Wiki documentation update

### ISSUE THREAD

**Issue by senpl** [maltaisn/recurpickerlib#13]
in https://github.com/maltaisn/recurpickerlib/wiki/Using-the-dialog-picker there is 
`onRecurrenceSelectedand and onCancelled`
it should probably on current version be
`// (it could mention in comments what works for old versions) 
onRecurrencePickerSelected and onRecurrencePickerCancelled`

**Comment by senpl** [comment]
Also r.format seem to not work for me. I guess it could easly be replaced by
`        Toast.makeText(this, "Picker dialog selected " +r.getPeriod(), Toast.LENGTH_LONG).show();`

**Comment by maltaisn** [comment]
Thanks I will fix that soon. You should use `RecurrenceFormat` for localized formatting instead of `toString()` which is used for debugging.
