### ISSUE TITLE
Simplify documentation for retriving recurrence index

### ISSUE THREAD

**Issue by senpl** [maltaisn/recurpickerlib#15]
Currently https://github.com/maltaisn/recurpickerlib/wiki/Using-the-recurrence-object states that `new Recurrence(byte[] array, int index) `
`index: index at which the recurrence starts in the byte array.`
To me setting it to 0 work as expected. I do not understand when on why would it ever change.
Simply use it with index 0 seem work.
So I guess mentioning default value 0 would be enough.

**Comment by maltaisn** [comment]
The use  for it was to avoid creating a new byte array when reading it from a ByteBuffer:
```kotlin
val bb = ByteBuffer.wrap(array)
// Stuff is read in-between
val recur = Recurrence(bb.array(), bb.position())
```
I don't think many people use a ByteBuffer anyway, but I thought it could be useful. I updated the documentation.
