### ISSUE TITLE
NullPointerException when not setting date formatter

### ISSUE THREAD

**Issue by guger** [maltaisn/recurpickerlib#17]
Since the date formatter is required, what about either making it a constructor parameter, or throwing an `IllegalStateException "Date Format must be set before calling show."` when those parameters are not set before calling `show`.

**Comment by maltaisn** [comment]
Actually there were default date formats in RecurrencePickerView but the dialog overrode them with null since they are set after the view initializes. I applied a temporary fix but I will do more refactoring later.
