### ISSUE TITLE
Determine how many days are selected for weekly repetition.

### ISSUE THREAD

**Issue by guger** [maltaisn/recurpickerlib#20]
I want to determine how many days are selected for weekly repetition.
e.g. Thu, Fri, Sun = 3 day

(How) is this possible?

**Comment by maltaisn** [comment]
You can do that:
```kotlin
val recurringDayCount = Integer.bitCount(recurrence.daySetting)
```
Since `daySetting` is a bit field of the days of the week set for weekly recurrence.

**Comment by guger** [comment]
Ok, thank you!
