### ISSUE TITLE
Computation error in findRecurrences

### ISSUE THREAD

**Issue by ol3th** [maltaisn/recurpickerlib#27]
Hello.

Found an error in the computation of recurrences.

Starting date set to Fri Aug 02, 2019
Repeat every 5 weeks on sun, fri, sat with no end date. 

Results: 
1. is on Sat Aug 03, 2019
2. is on Sun Sept 01, 2019
3. is on Fri Sept 06, 2019
4. is on Sat Sept 07, 2019
5. is on Sun Oct 06, 2019
6. is on Fri Oct 11, 2019
7. is on Sat Oct 12, 2019
8. is on Sun Nov 10, 2019

Expected result:
1. is on Sat Aug 03, 2019
2. is on Sun Aug 04, 2019
3. is on Fri Sept 06, 2019
4. is on Sat Sept 07, 2019
5. is on Sun Sept 08, 2019
6. is on Fri Oct 11, 2019
7. is on Sat Oct 12, 2019
8. is on Sun Oct 13, 2019

Does anyone have a quick fix?

**Comment by maltaisn** [comment]
Since the week starts on Sunday, the results you are getting are the correct ones. There's currently no way to change the start of the week to another weekday.

If you are a Google Calendar user, I invite you to try to make a recurring event with the same options. You'll get the same results.

**Comment by bitqube** [comment]
Ok. 
Could you share some insights to how change this? What changes needs to be done?
