### ISSUE TITLE
Animating Dialog

### ISSUE THREAD

**Issue by dejiapps** [maltaisn/recurpickerlib#28]
What would be the best way  to change the entering and exit animation for recurrence picker dialogs?

**Comment by maltaisn** [comment]
Are you using v2.0? I changed it a bit in this version and user is now responsible for showing all dialogs, so you can easily choose transitions as usually done with FragmentTransaction. You can see an example of this in the [demo app](https://github.com/maltaisn/recurpickerlib/blob/master/app/src/main/kotlin/com/maltaisn/recurpicker/demo/MainFragment.kt#L255)

If you not using the lastest version you'll be able to choose the transition for the recurrence list dialog in the same way but not transition for the custom recurrence picker dialog.
