### ISSUE TITLE
Recurrence At a specific date of month 

### ISSUE THREAD

**Issue by asgharkrk** [maltaisn/recurpickerlib#29]
Hi, Can anyone please guide me on how I can set recurrence of an event at a specific date of the month. Currently, if I select Period type "Month"  it only shows two options recurrence on the same date of the month or the same day of the month.

**Comment by maltaisn** [comment]
You need to change `RecurrencePickerDialog.startDate` or `RecurrencePickerFragment.startDate`. The events will happen on the same day of the month as this date if the "On the same day each month" option is selected.
