### ISSUE TITLE
Not able to use library with java project

### ISSUE THREAD

**Issue by KaanRF** [maltaisn/recurpickerlib#31]
Hello, 

Since we have already discuss nearly the same issue on your other project icondialog that I am living same situation on your recurpicker lib also. 

old issue --> https://github.com/maltaisn/icondialoglib/issues/35 

To make a test I have created 2 project on my pc one with kotlin the other one with java. So basically I wanted to run the demo on both project which has been mentioned here --> https://github.com/maltaisn/recurpickerlib/wiki/Using-the-library 

My observation is; 

When I use your library with the kotlin based created project everything is okey. Without problem I was able to run the demo. 

But when I use the library on the java project, Project has been frozen and I was not able to run even auto complete code and not able index the code. (Ctrl+click on the object will not refer to real place or class.) Even when I have done invalidate cache and restart it will work on first time then when I import sth related the libarary or call the some variable which has been related your library I got the problem permanently. 

So i thought maybe it can be help you to improve your library if some more people which has been faced the same issue like me. Maybe it is a problem for jetbrains or sth wrong on my PC(I have remove the android studio and re installed and currently version 4.0, so that is why I would not say a problem on my pc since your library worked with newly created kotlin project without problem.
). And also I am only doing some stuff as hobby on the android and I am not professional developer for android.  

That is why I ve uploaded the 2 project as zip on the PR. You can have a look. 
And I hope helps to you :) 

[JavaTrial.zip](https://github.com/maltaisn/recurpickerlib/files/4742072/JavaTrial.zip)
[KotlinTrial.zip](https://github.com/maltaisn/recurpickerlib/files/4742073/KotlinTrial.zip)

```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: com.google.services.firebase, org.intellij.plugins.markdown
```

**Comment by maltaisn** [comment]
The Java project worked fine for me. I had to fix a few things in MainActivity.java (adding a fragment container to the layout, initializing fragments) but after that everything could build and run. No indexing issues either (Ctrl + Click). I using AS 4.0 just like you.

It's hard to know what's the problem here, but it's most likely your computer. Do you have another computer on which you could test it by any chance?

**Comment by KaanRF** [comment]
I do not have other computer to check it. But maybe you can export ide settings and share with me ? maybe the problem is on my setting but I have already used the standart setting while installing the app.  

it stucks like below to find variable usages. 

![image](https://user-images.githubusercontent.com/3770937/84379975-5633f300-abef-11ea-8c80-95e3fe3ed875.png)
