### ISSUE TITLE
CustomPicker does not conform to Settings specified in RecurrencePickerSettings 

### ISSUE THREAD

**Issue by PeregrineFalcon** [maltaisn/recurpickerlib#36]
I have set RecurrencePickerSettings to only include DOES_NOT_REPEAT, DAILY, WEEKLY, and null (for custom). When a user selects a Custom they can still choose from the dropdown a list that includes Monthly and Yearly. 

Is there a way to ensure the settings are enforced in the Custom dialog view?

**Comment by maltaisn** [comment]
That's the intended behavior, presets are only meant to give the user a quick access to more common choices. 

There actually [used to be a way to do that](https://github.com/maltaisn/recurpickerlib/blob/v1.6.0/recurpicker/src/main/java/com/maltaisn/recurpicker/RecurrencePickerSettings.java#L161) but I didn't add it back after doing the rewrite. I could do that if you need.
