### ISSUE TITLE
Support from API 19

### ISSUE THREAD

**Issue by JobGetabu** [maltaisn/recurpickerlib#6]
This great library can support from 19?

**Comment by JobGetabu** [comment]
or use tools:overrideLibrary="com.maltaisn.recurpicker" to force usage (may lead to runtime failures)
Can we get an update for support from 19 ?

**Comment by maltaisn** [comment]
No, I'm sorry, that would require changing a lot of the code. I just checked and there is now less than 15% device on API 19 and lower, it is probably best to stop supporting it. In one year this will be even lower, 10% or maybe less.

**Comment by davidvavra** [comment]
+1 for API 19+ support. It might be OK to start API 21+ for new apps, but existing apps can't ditch 15% of their userbase.

**Comment by maltaisn** [comment]
I'll see what I can do.

**Comment by maltaisn** [comment]
Library was backported to API 19 in [`v1.4.0`](https://github.com/maltaisn/recurpickerlib/commit/04b703eb81ad99d257e3bce60293e294a35af0ff)

**Comment by davidvavra** [comment]
Wow thanks a lot, @maltaisn! Users of Settle Up will be now able to setup recurring transactions also on API 19 :)
