### ISSUE TITLE
Repeat monthly

### ISSUE THREAD

**Issue by kosotd** [maltaisn/recurpickerlib#8]
Hello. When I select REPEAT OPTION: "Custom..." -> REPEAT MONTHLY, I see two option: "on the same day each month" and "on every forth Tuesday". How I can to remove or change these options?

**Comment by maltaisn** [comment]
It's not currently possible to change these options. Can you give me an example of what you would change it for? Also there is no way to hide them. If I added a way to do so, what should be the default option (same day of month or same day of week)?

**Comment by kosotd** [comment]
At this time I took your library, added her in my project and forcibly hided RadioGroup with these options (monthlySettingsGroup.setVisibility(View.GONE)). The default value is "same day of month". And besides this I changed
"string name="rp_repeat_monthly_same_day"on the same day each month/string" to 
"string name="rp_repeat_monthly_same_day"/string"
I hope you do not mind it. Thank you.

**Comment by maltaisn** [comment]
So you added the library directly in your project without Gradle? Do you still need an option to hide the monthly settings?

**Comment by kosotd** [comment]
Yes. I added it directly as module. No, I hid it by changing your code. Сan I use your library like this?

**Comment by maltaisn** [comment]
You can if you want, nothing prevents you. The only downside for you is that it's more work to update it to a new version when you only change the version number if using it with Gradle.
