### ISSUE TITLE
Localization problems

### ISSUE THREAD

**Issue by davidvavra** [maltaisn/recurpickerlib#9]
Hi, I wanted to translate the library to Czech language (and others), but I face a few problems:

- you are using some non-standard notation for string parameters, e.g. `on every {0} {1}`. I don't see why not to use standard parameters like `%s`. My translators are used to standard format and explaining them something else would be hard.
- your custom parameter format ignores plurals. Some languages (like Czech), don't have just two forms (singular and plural), but multiple. For example "every month" is "každý měsíc", "every 2 months" is "každé 2 měsíce" and "every 5 months" is "každých 5 měsíců". I can't use plurals now, so Czech translation would be wrong. Android has plurals built-in, so why not to use it.
- I would argue against string arrays, strings.xml should be only about translations and not about UI structure. It has disadvantage that some strings are repeating ("Forever"). So I would place only individual strings in strings.xml and build lists from them in the code. But it's not a blocker.
- name of week days and abbreviated week days are part of Calendar API, you don't need to put them into translations. It's unnecessary clutter and increases APK size.
- you can remove a string "rp_cancel" and replace it with "android.R.string.cancel"
- you should put instructions for the translation into `translation_description` attribute instead of a comment. Tools for translators read it and display it automatically as a context.

What do you think? If you solve this, I'm willing to translate it into Czech myself and then upload it to GetLocalization platform where users of my app (Settle Up) translate the app to 18 languages. When it's translated I can send PR for all translated languages.

**Comment by maltaisn** [comment]
I can definitively change MessageFormat to String.format and plurals and add `translation_description` attributes.

I don't know about giving up string arrays, they do prevent a lot of boilerplate. I could change some of them (`rp_recur_formats`, `rp_end_formats` and a few others) closely related to the UI, but for others (`rp_ordinal_numbers`, days of the week) it seems more relevant to keep them. GetLocalization platform seem to support them so it shouldn't be a problem as you said.

The rationale behind having days of the week strings was that users using a language that is not translated would not see half of the UI in their language and half in the default language as they would have had if I were using the Calendar API and Android strings. This can be solved by using `resConfigs` for Android strings but not for the Calendar strings. But then I guess that with potentially 18 languages it would affect only a tiny proportion of the users. What do you think?

Do you think there will be any UI issues for some languages? The frequency part of the UI shows for example "Every 3 days" but are there any languages which would need the number to be displayed first? It wouldn't be very hard to fix this so I'd rather do it now.

**Comment by davidvavra** [comment]
Hi, thanks for a great response. 
- I have an idea about string arrays - how about putting them into a separate file where you will only reference translations like this: `<string-array name="test">
        <item>@string/translation</item>
    </string-array>`. This way you can reduce the boilerplate and keep strings.xml free of implementation details.
- I understand the rationale behind the Calendar strings. But as you said if we have 18 languages it will be very minor issue. And I saw many apps do this as well. However in Settle Up I solve it like this:

build.gradle:

    def supportedLanguages = ["en", "cs", "de", "fi", "it", "ru", "es", "pl", 'lt', 'vi', 'fr', 'sk', 'sq', 'pt', 'zh-rTW', 'sv']
    resConfigs supportedLanguages
    buildConfigField "String[]", "SUPPORTED_LANGUAGES", "{\"" + supportedLanguages.join("\",\"") + "\"}"

and then when I format anything using Calendar API, I pass locale from this method:

    fun supportedLocale(): Locale {
        val default = Locale.getDefault()
        return if (BuildConfig.SUPPORTED_LANGUAGES.contains(default.language)) {
            default
        } else {
            Locale.UK // UK has nicer formatting for most of the world
        }
    }

So maybe your library can offer this as optional feature. User of the library could override some list of supported languages (which can be taken from resconfigs via BuildConfig)

- You should not have a string "every" on it's own, it should be part of the plural. Because it changes (see my example in previous post). If it's part of the plural, people could put number first for their language (but I'm not aware about a language where they put numbers first).

**Comment by maltaisn** [comment]
- Great idea for string arrays, I'll do it for all of them.
- Adding the option for supported locales adds complexity to the library where any developper would expect `resConfigs` to work. I still believe manually entering and translating days of week outweighs the use of Calendar strings, even if that would add a few kB.
- For the locale dependant UI changes I'll keep it this way for now and if any languages needs it I could add locale specific layout files for the frequency views and include it in main layout. I'll include "every" as part of the plural.

**Comment by davidvavra** [comment]
Imho if we have 18 languages, most of the developers won't care that resConfig doesn't work. And if they do, you could have advanced feature where the developer can specify supported languages. It's 12 strings x 18 languages = 216 strings and extra work for translators. But I will leave the decision up to you, it's not a blocker.

**Comment by maltaisn** [comment]
Turns out I have no choice but to use string arrays for days of the week, because the plural form is used in certain languages. In English "on every third Wednesday" becomes "tous les troisièmes mercredis" in French (notice the "s" on "mercredis") I don't think there's an option for that in the Calendar API.

So that leaves me with two options:
- Same as now, format 3 strings set together to form another string: "on every [nth] [day of week]". This combines the days of the week array with the ordinal numbers array and a format string "on every %1$s %2$s". This approach is significantly harder to understand for a translator.
- Same approach as Sublime Picker, look at their [`arrays.xml`](https://github.com/vikramkakkar/SublimePicker/blob/master/sublimepickerlibrary/src/main/res/values/arrays.xml) file: a string array for each day of the week. This results in to translate (35 vs 12) but it's more straightforward and translators can copy-paste most of it.

Also you told me to use `translation_description` but I can't find any documentation on it anywhere, and on the GetLocalization platform they specify that we should use `<string name="menu_stop" comment="After item Start in Menu">Stop</string>` in the [Android XML file format](https://www.getlocalization.com/docs/file-formats/android-strings-xml/).

**Comment by davidvavra** [comment]
This localization stuff is tricky :)

So in French every first Wednesday and every third Wednesday has different ending for Wednesday?

You can't use the first option, because the "on every" part changes in some languages based on the name of the day. In Czech "on every first Monday" is "každé první pondělí" but "on every first Wednesday" is "každou první středu" (notice "každé" vs "každou"). So you would need the second option, but I suggest not to make 4 strings for first, second, third and fourth, but do it with numbers (1., 2., 3., 4.). "last" can be additional string. That will save some combinations. 

You are right about the `translation_description`. I found it in official [firebase-ui library](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/res/values/strings.xml) so I thought it's standard. But I also can't find it anywhere and GL doesn't support it, so it would be better to replace it with `comment`.

**Comment by maltaisn** [comment]
I'm done making the changes. Would it be better if I create my own project on GetLocalization? I could comment each string there and set max lengths instead of putting cluttering `comment` attributes in the `strings.xml` file.

**Comment by davidvavra** [comment]
Great! Can you create a PR so I can have a look on it before the release?

Each project should have own GL project, but I'm afraid it would be too hard to persuade my translators to join your project. Plus I have a free account and they recently introduced harder monetization so you might be charged. My plan is to copy-paste your translations into my app strings.xml directly, upload it to GL like always and send you PR once most of the languages are translated. But it's up to you.

I like comments to be inside strings.xml file, I like that it's linked with code and versioned in Git. I won't forget to update comments when I update strings.

**Comment by maltaisn** [comment]
I made the commit. I didn't include comments for the French strings, only for the English ones. Should they be translated too?

**Comment by davidvavra** [comment]
I have looked at it, good job, just one comment:
- You can remove the `rp_cancel` string, use android.R.string.cancel instead

You don't have to translate comments to French, comments are always in the default language.

**Comment by maltaisn** [comment]
Alright, do you plan on translating to other languages soon? If not I'll release the new version.

**Comment by davidvavra** [comment]
I will translate it to Czech through GL and send you all of the files once more of them get translated, go ahead with the release.

**Comment by davidvavra** [comment]
Oh I forgot about one thing: for plurals, you also need to include a quantity "few", even for English which doesn't need it. It's a limitation of GetLocalization, it wouldn't be offered otherwise. Like this:

    <plurals name="expense">
        <item quantity="one">%s expense</item>
        <item quantity="few">%s expenses</item>
        <item quantity="other">%s expenses</item>
    </plurals>
